import Mathlib

/-!
**`thm:complete-prime-local`(iii)'s `(A11)`/`(A12)` order-of-vanishing infrastructure.**
The manuscript works "in `\mathbb F_p[y_2,\ldots,y_p]/J^p`" and speaks of the "`J`-adic order"
of an element `D_{\mathbf c}(y)`. Since `J` (the ideal generated by the variables) is the
standard irrelevant ideal of a graded polynomial ring, `J^k` is exactly the degree-`\ge k` part,
and the `J`-adic order of a nonzero polynomial is simply its **minimum total degree** among
monomials with nonzero coefficient — this file works directly with that notion in the
(untruncated) polynomial ring, which is equivalent to the truncated-ring statements for the
purposes of comparing orders below any fixed bound.
-/

namespace CongruenceTheory

open MvPolynomial

variable {R : Type*} [CommSemiring R]

/-- The total degree of a monomial exponent `d`, as a `Finsupp.weight` with the all-ones
weight (matching this project's `Finsupp.weight`-based weighted-homogeneity idiom). -/
noncomputable def monoDeg (d : ℕ →₀ ℕ) : ℕ := Finsupp.weight (fun _ : ℕ => (1 : ℕ)) d

theorem monoDeg_eq_sum (d : ℕ →₀ ℕ) : monoDeg d = d.sum fun _ e => e := by
  simp [monoDeg, Finsupp.weight_apply, Finsupp.sum]

@[simp] theorem monoDeg_zero : monoDeg (0 : ℕ →₀ ℕ) = 0 := by simp [monoDeg_eq_sum]

theorem monoDeg_add (d₁ d₂ : ℕ →₀ ℕ) : monoDeg (d₁ + d₂) = monoDeg d₁ + monoDeg d₂ := by
  simp only [monoDeg, Finsupp.weight_apply]
  rw [Finsupp.sum_add_index'] <;> simp

/-- **`φ` has order exactly `k`**: every nonzero-coefficient monomial has degree `\ge k`, and
some nonzero-coefficient monomial has degree exactly `k`. This is the `J`-adic order of `φ`,
where `J` is the irrelevant ideal (generated by all variables). -/
def MinDeg (φ : MvPolynomial ℕ R) (k : ℕ) : Prop :=
  (∀ d ∈ φ.support, k ≤ monoDeg d) ∧ ∃ d ∈ φ.support, monoDeg d = k

theorem MinDeg.ne_zero {φ : MvPolynomial ℕ R} {k : ℕ} (h : MinDeg φ k) : φ ≠ 0 := by
  obtain ⟨d, hd, -⟩ := h.2
  intro hφ
  rw [hφ] at hd
  simp at hd

theorem MinDeg.le {φ : MvPolynomial ℕ R} {k : ℕ} (h : MinDeg φ k) {d : ℕ →₀ ℕ}
    (hd : d ∈ φ.support) : k ≤ monoDeg d := h.1 d hd

/-- **Order of a sum is `\ge` the min of the orders**, always. -/
theorem MinDeg.add_ge {φ ψ : MvPolynomial ℕ R} {k₁ k₂ : ℕ} (h1 : MinDeg φ k₁)
    (h2 : MinDeg ψ k₂) : ∀ d ∈ (φ + ψ).support, min k₁ k₂ ≤ monoDeg d := by
  intro d hd
  rw [MvPolynomial.mem_support_iff, MvPolynomial.coeff_add] at hd
  by_cases hdφ : coeff d φ = 0
  · have hdψ : coeff d ψ ≠ 0 := by intro h; rw [hdφ, h] at hd; simp at hd
    exact le_trans (min_le_right _ _) (h2.le (MvPolynomial.mem_support_iff.mpr hdψ))
  · exact le_trans (min_le_left _ _) (h1.le (MvPolynomial.mem_support_iff.mpr hdφ))

/-- **Order of a product is `\ge` the sum of the orders**, always. -/
theorem MinDeg.mul_ge {φ ψ : MvPolynomial ℕ R} {k₁ k₂ : ℕ} (h1 : MinDeg φ k₁)
    (h2 : MinDeg ψ k₂) : ∀ d ∈ (φ * ψ).support, k₁ + k₂ ≤ monoDeg d := by
  intro d hd
  rw [MvPolynomial.mem_support_iff, MvPolynomial.coeff_mul] at hd
  by_contra hcon
  push_neg at hcon
  apply hd
  apply Finset.sum_eq_zero
  rintro ⟨d1, d2⟩ hmem
  simp only [Finset.mem_antidiagonal] at hmem
  by_cases hd1 : coeff d1 φ = 0
  · simp [hd1]
  by_cases hd2 : coeff d2 ψ = 0
  · simp [hd2]
  exfalso
  have hge1 : k₁ ≤ monoDeg d1 := h1.le (MvPolynomial.mem_support_iff.mpr hd1)
  have hge2 : k₂ ≤ monoDeg d2 := h2.le (MvPolynomial.mem_support_iff.mpr hd2)
  have hdeq : monoDeg d = monoDeg d1 + monoDeg d2 := by rw [← hmem, monoDeg_add]
  omega

#print axioms monoDeg_add
#print axioms MinDeg.add_ge
#print axioms MinDeg.mul_ge

end CongruenceTheory
