import Mathlib

/-!
**`cor:triangular-independence`'s general algebraic core**: "a triangular unit-diagonal Jacobian
implies algebraic independence." This file formalizes the self-contained algebraic fact behind
the corollary, independent of the specific combinatorics of `K_j(p)`.

**Precise scope**: the manuscript's own construction only ever needs the special case where each
`L_j`, viewed as a polynomial in the "new" variable `z_j` over the subring generated by
`z_0,\ldots,z_{j-1}`, is *affine of degree exactly 1* with unit leading coefficient (this is what
"the coefficient of `z_j` in `L_j` is a `p`-unit, and `z_m` cannot occur in `L_j` for `m>j`"
amounts to once one notes `K_j(p)`'s total-degree grading forces `X_{jp}` to appear at most to
the first power with no cross terms — the only monomial of `K_j(p)` containing `X_{jp}` at all is
the bare monomial `X_{jp}` itself, since that already saturates the total degree `jp`). This file
formalizes exactly that case: `L j = C (c j) * X j + g j` with `c j` a unit and `g j` not
involving variable `j` or higher. This is a faithful, sufficient formalization of "triangular
unit-diagonal Jacobian" for every application in this project; the fully general Jacobian
criterion (for `L_j`'s that are merely triangular of arbitrary degree in `z_j`, not just affine)
is strictly more general and is not attempted here.

**Method**: build an explicit two-sided algebra-endomorphism inverse `triInv : ℕ → MvPolynomial ℕ
K` solving `z_j` in terms of `L_0,\ldots,L_j` by recursion on `j` (`triStage`, a stage-indexed
family of partial solutions, together with a stabilization lemma showing the stage-`n` solution
at index `i<n` no longer changes for any larger stage). `aeval triInv` is then a genuine
two-sided inverse of `aeval L` on generators, giving injectivity of `aeval L` directly — i.e.
`AlgebraicIndependent K L`, matching Mathlib's own definition of algebraic independence.

**Honest scope note**: this closes the general algebraic fact completely (zero `sorry`). Applying
it to the specific `L_1=C_p`, `L_j=p^{-e_p(j)}K_j(p)` of `cor:triangular-independence` itself —
verifying the affine-in-`z_j`/unit-coefficient hypotheses hold for these particular polynomials,
which needs the total-degree grading argument sketched above — is not attempted here.
-/

namespace CongruenceTheory

open MvPolynomial

variable {K : Type*} [Field K]

/-- `aeval` only depends on a substitution's values at the variables actually occurring in a
polynomial. -/
theorem aeval_congr_of_vars {p : MvPolynomial ℕ K} {σ σ' : ℕ → MvPolynomial ℕ K}
    (h : ∀ i ∈ p.vars, σ i = σ' i) : aeval σ p = aeval σ' p := by
  simp only [aeval_def]
  apply eval₂_congr
  intro i d hd hcoeff
  exact h i ((mem_vars_iff_mem_support i).mpr ⟨d, mem_support_iff.mpr hcoeff, hd⟩)

/-- The stage-`n` partial inverse substitution: `triStage c g n i` solves `z_i` in terms of
`L_0,\ldots,L_i` whenever `i < n` (and is an unused placeholder otherwise). Built by ordinary
recursion on the stage `n`. -/
noncomputable def triStage (c : ℕ → Kˣ) (g : ℕ → MvPolynomial ℕ K) : ℕ → ℕ → MvPolynomial ℕ K
  | 0 => X
  | n + 1 => fun k =>
      if k = n then
        MvPolynomial.C ((c n : K)⁻¹) * (X n - MvPolynomial.aeval (triStage c g n) (g n))
      else
        triStage c g n k

theorem triStage_succ_of_ne (c : ℕ → Kˣ) (g : ℕ → MvPolynomial ℕ K) {n i : ℕ} (h : i ≠ n) :
    triStage c g (n + 1) i = triStage c g n i := by
  show (if i = n then _ else triStage c g n i) = triStage c g n i
  rw [if_neg h]

theorem triStage_succ_of_lt (c : ℕ → Kˣ) (g : ℕ → MvPolynomial ℕ K) {n i : ℕ} (h : i < n) :
    triStage c g (n + 1) i = triStage c g n i :=
  triStage_succ_of_ne c g (Nat.ne_of_lt h)

theorem triStage_succ_self (c : ℕ → Kˣ) (g : ℕ → MvPolynomial ℕ K) (n : ℕ) :
    triStage c g (n + 1) n =
      MvPolynomial.C ((c n : K)⁻¹) * (X n - MvPolynomial.aeval (triStage c g n) (g n)) := by
  show (if n = n then _ else triStage c g n n) = _
  rw [if_pos rfl]

/-- The stage-`n` solution at index `i` stabilizes for every stage `n > i`. -/
theorem triStage_stable (c : ℕ → Kˣ) (g : ℕ → MvPolynomial ℕ K) {i : ℕ} :
    ∀ {n}, i < n → triStage c g n i = triStage c g (i + 1) i := by
  intro n hn
  induction n, hn using Nat.le_induction with
  | base => rfl
  | succ n hn ih => rw [triStage_succ_of_lt c g hn, ih]

/-- The stabilized inverse substitution: `triInv i` solves `z_i` in terms of `L_0,\ldots,L_i`,
independent of any stage. -/
noncomputable def triInv (c : ℕ → Kˣ) (g : ℕ → MvPolynomial ℕ K) (i : ℕ) : MvPolynomial ℕ K :=
  triStage c g (i + 1) i

theorem triStage_eq_triInv_of_lt (c : ℕ → Kˣ) (g : ℕ → MvPolynomial ℕ K) {n i : ℕ} (h : i < n) :
    triStage c g n i = triInv c g i :=
  triStage_stable c g h

/-- **The core recursive fact**: `triInv` really does invert `L` on every index. -/
theorem aeval_triInv_L (c : ℕ → Kˣ) (g : ℕ → MvPolynomial ℕ K)
    (hg : ∀ j, ∀ i ∈ (g j).vars, i < j) :
    ∀ j, MvPolynomial.aeval (triInv c g) (MvPolynomial.C ((c j : K)) * X j + g j) = X j := by
  intro j
  have hstep : MvPolynomial.aeval (triInv c g) (g j) =
      MvPolynomial.aeval (triStage c g j) (g j) := by
    apply aeval_congr_of_vars
    intro i hi
    exact (triStage_eq_triInv_of_lt c g (hg j i hi)).symm
  have hτj : triInv c g j = MvPolynomial.C ((c j : K)⁻¹) *
      (X j - MvPolynomial.aeval (triStage c g j) (g j)) := by
    show triStage c g (j + 1) j = _
    exact triStage_succ_self c g j
  rw [map_add, map_mul, aeval_C, aeval_X, hstep, hτj]
  have hcancel : (algebraMap K (MvPolynomial ℕ K)) (c j : K) *
      (MvPolynomial.C ((c j : K)⁻¹) *
        (X j - MvPolynomial.aeval (triStage c g j) (g j))) =
      X j - MvPolynomial.aeval (triStage c g j) (g j) := by
    rw [MvPolynomial.algebraMap_eq, ← mul_assoc, ← MvPolynomial.C_mul]
    rw [mul_inv_cancel₀ (Units.ne_zero (c j))]
    simp
  rw [hcancel]
  ring

/-- **`cor:triangular-independence`'s general algebraic core, fully formalized.** If each `L j`
is affine of degree `1` in `X j` with unit leading coefficient `c j`, and depends otherwise only
on the strictly smaller variables (`g j`'s vars all `< j`), then `L` is algebraically
independent over `K`. -/
theorem algebraicIndependent_of_triangular (L : ℕ → MvPolynomial ℕ K) (c : ℕ → Kˣ)
    (g : ℕ → MvPolynomial ℕ K) (hL : ∀ j, L j = MvPolynomial.C ((c j : K)) * X j + g j)
    (hg : ∀ j, ∀ i ∈ (g j).vars, i < j) :
    AlgebraicIndependent K L := by
  have hinv : ∀ j, MvPolynomial.aeval (triInv c g) (L j) = X j := by
    intro j; rw [hL]; exact aeval_triInv_L c g hg j
  have hcomp : (MvPolynomial.aeval (triInv c g)).comp (MvPolynomial.aeval L) =
      AlgHom.id K (MvPolynomial ℕ K) := by
    apply MvPolynomial.algHom_ext
    intro i
    simp only [AlgHom.comp_apply, aeval_X, AlgHom.id_apply]
    exact hinv i
  have hleft : Function.LeftInverse (MvPolynomial.aeval (triInv c g)) (MvPolynomial.aeval L) := by
    intro p
    have := AlgHom.congr_fun hcomp p
    simpa using this
  exact hleft.injective

#print axioms algebraicIndependent_of_triangular

end CongruenceTheory
